import { Footer, Header } from '@/partials'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Image from 'next/image'
import '../styles/globals.css'

const poopins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    variable: '--font-poopins',
})

export const metadata: Metadata = {
    title: 'Restaurant App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={`${poopins.variable} scroll-smooth antialiased`}>
            <body className="font-poppins h-screen">
                <div className="h-screen w-full fixed">
                    <Image
                        src="/food/banner.png"
                        alt="background"
                        fill
                        className="object-cover -z-10 blur-2xl contrast-75"
                        priority
                    />
                </div>

                <div className="max-w-6xl mx-auto min-h-screen p-10 isolate bg-white/20 shadow-md">
                    <Header />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    )
}
