export default function LogoUtils() {
    return (
        <div>
            <h1 className="uppercase font-bold text-xl">Restaurant App</h1>
            <p className="text-xs">Generated by create next app</p>
        </div>
    )
}
